//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evoting_Application.Models
{
    using System;
    using System.Web;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentUniqueID { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<int> VoterId { get; set; }
        public Nullable<int> RoleID { get; set; }
        public HttpPostedFileBase Aadhar { get; set; }
        public HttpPostedFileBase Pan { get; set; }
        public virtual Role Role { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
