//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evoting_Application.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EvotingApplicationEntities : DbContext
    {
        public EvotingApplicationEntities()
            : base("name=EvotingApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Voter> Voters { get; set; }
    
        public virtual ObjectResult<CandidateDetailsForAdmin_Result> CandidateDetailsForAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CandidateDetailsForAdmin_Result>("CandidateDetailsForAdmin");
        }
    
        public virtual ObjectResult<CandidateDetailsListForAdmin_Result> CandidateDetailsListForAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CandidateDetailsListForAdmin_Result>("CandidateDetailsListForAdmin");
        }
    }
}
