//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evoting_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.Candidates = new HashSet<Candidate>();
            this.Documents = new HashSet<Document>();
            this.Voters = new HashSet<Voter>();
            RoleID = 1;
        }
    
        public int VoterId { get; set; }
        [Required(ErrorMessage ="Field cannot be empty")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Field cannot be empty")]

        public string Name { get; set; }
        [Required(ErrorMessage = "Field cannot be empty")]
        //[MinLength(8, ErrorMessage = "Minimum 8 character password required")]
        //[MaxLength(12, ErrorMessage = "Maximum 12 character password required")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Field cannot be empty")]

        public System.DateTime Birthdate { get; set; }
        [Required(ErrorMessage = "Field cannot be empty")]

        public string Gender { get; set; }
        [Required(ErrorMessage = "Field cannot be empty")]

        public string Location { get; set; }
        [Required(ErrorMessage = "Field cannot be empty")]

        public string Address { get; set; }
        [Display(Name ="Mobile Number")]
        [Required(ErrorMessage = "Field cannot be empty")]
        [MinLength(10, ErrorMessage = "Enter 10 digit number")]
        [MaxLength(10,ErrorMessage ="Enter 10 digit number")]


        public string MobileNumber { get; set; }
        public int RoleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate> Candidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voter> Voters { get; set; }
    }
}
