//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evoting_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Voter
    {
        [Display(Name ="Voter Unique ID")]
        public int VoterUniqueID { get; set; }
        [Display(Name = "Has Voted")]

        public bool HasVoted { get; set; }
        [Display(Name = "Request Status")]

        public bool RequestStatus { get; set; }
        public bool Approval { get; set; }
        [Display(Name = "Voter  ID")]

        public int VoterId { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
