// <auto-generated />
using EF_Code.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Code.Migrations
{
    [DbContext(typeof(InfoDBContext))]
    [Migration("20221018081422_tphMigration")]
    partial class tphMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EF_Code.Models.Person", b =>
                {
                    b.Property<int>("PersonUniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonUniqueId"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.HasKey("PersonUniqueId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("EF_Code.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("StaffId");

                    b.ToTable("Staffs");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Staff");
                });

            modelBuilder.Entity("EF_Code.Models.Doctor", b =>
                {
                    b.HasBaseType("EF_Code.Models.Staff");

                    b.Property<string>("Specialiazation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Doctor");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            Name = "Suresh",
                            Salary = 9000,
                            Specialiazation = "Heart"
                        },
                        new
                        {
                            StaffId = 2,
                            Name = "Om",
                            Salary = 90,
                            Specialiazation = "Cancer"
                        });
                });

            modelBuilder.Entity("EF_Code.Models.Nurse", b =>
                {
                    b.HasBaseType("EF_Code.Models.Staff");

                    b.Property<int>("RoomAllocated")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Nurse");

                    b.HasData(
                        new
                        {
                            StaffId = 3,
                            Name = "deepika",
                            Salary = 988,
                            RoomAllocated = 201
                        },
                        new
                        {
                            StaffId = 4,
                            Name = "Alia",
                            Salary = 8766,
                            RoomAllocated = 403
                        });
                });

            modelBuilder.Entity("EF_Code.Models.WardBoy", b =>
                {
                    b.HasBaseType("EF_Code.Models.Staff");

                    b.Property<int>("floor")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("WardBoy");

                    b.HasData(
                        new
                        {
                            StaffId = 5,
                            Name = "Shree",
                            Salary = 455,
                            floor = 201
                        },
                        new
                        {
                            StaffId = 6,
                            Name = "Rakesh",
                            Salary = 974,
                            floor = 403
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
